### PR TITLE
Build against PHP 7.0

### PR DESCRIPTION
**Pull request by cebe**
Composer fails from an exception of this library on PHP 7 so I enabled testing against PHP7 to see if unit tests pass.
https://travis-ci.org/yiisoft/yii2/jobs/52251656#L1496

### CODE REVIEW

**Comment by cebe** [comment]
Wow, all tests are failing with the same error message: https://travis-ci.org/Seldaek/jsonlint/jobs/52274492

```
Undefined offset: 1
/home/travis/build/Seldaek/jsonlint/src/Seld/JsonLint/JsonParser.php:317
/home/travis/build/Seldaek/jsonlint/tests/JsonParserTest.php:42
```
https://github.com/Seldaek/jsonlint/blob/master/src/Seld/JsonLint/JsonParser.php#L317

Not sure about the cause, will look into this later.

**Comment by stof** [comment]
This looks like a bug in the array handling in PHP 7

**Comment by Seldaek** [comment]
Yeah I've hit that when trying to run composer tests against php7. I did not have time to investigate but if you do it'd be great to report the bug.. Because it seems to be a PHP bug :)

**Comment by fonsecas72** [comment]
composer/composer#3806 (comment)

**Comment by fonsecas72** [comment]
ffr: https://bugs.php.net/bug.php?id=69172

**Comment by stof** [comment]
@Seldaek I suggest merging it (this will allow to see when PHP 7 fixes the issue)

**Comment by Seldaek** [comment]
The fix is in already, but we need to wait for travis. Anyway yes if it allows failure let's merge already and remove allow_failure when possible.

**Comment by fonsecas72** [comment]
@Seldaek in case you didn't notice the travis already updated PHP7.

**Comment by Seldaek** [comment]
Ah nice I'll remove the flag then, thanks :)

**Pull request merged**
