### PR TITLE
Update phpunit allowed versions

### PR DESCRIPTION
**Pull request by remicollet**
To have namespace used since 4267a75cb5c3555319f17b35f5031f5590560345

### CODE REVIEW

**Comment by staabm** [comment]
hmm interessting that travis builds didn't error for 4267a75

**Comment by remicollet** [comment]
> hmm interessting that travis builds didn't error for 4267a75

composer pull 4.8.36 so it works.

**Comment by Seldaek** [comment]
Thanks

**Comment by stof** [comment]
yeah, unless you use `--prefer-lowest`, composer will choose the highest version (and so will not validate that your lower bound is the right one)

**Pull request merged**
