### PR TITLE
Fixed code for PHP7 and added it to travis build 

### PR DESCRIPTION
**Pull request by fonsecas72**

### CODE REVIEW

**Comment by stof** [comment]
This looks weird to me. We want these arrays to be numerically indexed, so we should not need to preserve keys.
This rather looks like a bug in the PHP 7 array handling which should be reported to the PHP team

**Comment by fonsecas72** [comment]
It looks weird to me too, I just notice that the docs say the opposite.
> preserve_keys
Note that array_slice() will reorder and reset the numeric array indices by default. You can change this behaviour by setting preserve_keys to TRUE.

Anyway, shouldn't the tests be failing by now?
I'll look into this again. I never open an issue to the PHP before but I guess there always a first time.
Can't we summon anyone to have a look at this? Not that this is urgent though.

**Comment by fonsecas72** [comment]
@stof https://bugs.php.net/bug.php?id=69172

**Comment by stof** [comment]
> Anyway, shouldn't the tests be failing by now?

Which tests are you talking about ? If you talk about the JsonLint tests, see #27 which enabled the Travis build before you and you will see that they are failing. If you talk about the PHP tests, the fact that there is a regression probably means that they don't have a test covering this particular case yet

**Comment by fonsecas72** [comment]
@stof I mean the jsonlint test for this PR. I've also activated PHP7 build in this PR and they are all green. I changed the php default behaviour of the array_slice function so shouldn't they (the php < 7 ones) be failing?

**Comment by stof** [comment]
@fonsecas72 in the particular case you are changing, no. But only because your slice is the beginning of the array.

**Comment by fonsecas72** [comment]
@stof I misunderstood the ```preserve_keys``` parameter and I was being dumb. Sorry for wasting your time.

**Pull request closed without merging**
